import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const moonglade = localFont({
  src: [
    { path: "./fonts/moongladeLight.ttf", weight: "100", style: "normal" },
    { path: "./fonts/moongladeRegular.ttf", weight: "400", style: "normal" },
    { path: "./fonts/moongladeBold.ttf", weight: "700", style: "bold" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${moonglade.className} antialiased object-center`}>
        <div className="flex justify-center w-dvw h-dvh p-4 md:py-20 md:px-14 xl:px-auto">
          <div className="border-8 border-black w-full xl:w-10/12 xl:max-w-screen-l h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
